# use kubectl create -f support-archives/archive.yaml -n ecosystem instead of apply
apiVersion: k8s.cloudogu.com/v1
kind: SupportArchive
metadata:
  generateName: support-archive-sample-
spec:
  contentTimeframe:
    startTime: "2025-09-14T11:10:00Z" # use default contentTimeframe with empty metav1.Time
    endTime: "2025-09-22T11:20:00Z"
  excludedContents:
    systemState: true
    sensitiveData: true
    events: false
    logs: true
    volumeInfo: true
    systemInfo: true
