apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
  name: blueprint-postgres-testing
spec:
  blueprint: |
    {
      "blueprintApi":"v2",
      "dogus":[
        {
          "name":"official/postgresql",
          "version":"14.17-1",
          "targetState":"present",
          "platformConfig": {
            "resource": {
              "minVolumeSize": "1Gi"
            }
          }
        }
      ]
    }
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  allowDoguNamespaceSwitch: false
