apiVersion: k8s.cloudogu.com/v1
kind: Component
metadata:
  name: k8s-dogu-operator
spec:
  name: k8s-dogu-operator
  namespace: k8s
  version: 3.22.0
#  valuesYamlOverwrite: |-
#    controllerManager:
#      env:
#        authRegistrationEnabled: true
#        disablePostfixDependencyCheck: true