apiVersion: k8s.cloudogu.com/v2
kind: Dogu
metadata:
  name: nginx-static
  labels:
    app: ces
spec:
  name: k8s/nginx-static
  version: 1.26.3-1
#  you can mount files from configmaps and secrets
#  this file is then be reachable under <FQDN>/static/<FILENAME>
#  additionalMounts:
#    - name: html-config
#      sourceType: ConfigMap
#      volume: customhtml
