apiVersion: k8s.cloudogu.com/v1
kind: ServiceAccountRequest
metadata:
  name: grafana-prometheus-auth
  namespace: ecosystem
spec:
  optional: true
  consumer: grafana
  consumerType: Dogu
  producer: prometheus
  secretRef:
    name: grafana-prometheus-credentials
  params:
    options:
      consumer:
        - "grafana"
#    args:
#      - "--verbose"
#  rotation:
#    enabled: true
#    rotation: "@weekly"