apiVersion: k8s.cloudogu.com/v1
kind: ServiceAccountRequest
metadata:
  name: grafana-nexus-auth
  namespace: ecosystem
spec:
  optional: true
  consumer: "grafana"
  consumerType: "Dogu"
  producer: "nexus-producer"
  secretRef:
    name: "grafana-nexus-credentials"
  params:
    options:
      fullAccessRepository:
        - "raw-internal"
      permissions:
        - "nx-repository-view-*-*-read"
    args:
      - "--verbose"
  rotation:
    enabled: true
    rotation: "@weekly"