apiVersion: k8s.cloudogu.com/v2
kind: ServiceAccountRequest
metadata:
  name: grafana-prometheus-auth
  namespace: ecosystem
spec:
  optional: true
  consumer: grafana
  consumerType: Dogu
  producer: k8s-prometheus
  secretRef:
    name: grafana-prometheus-credentials
#  rotation:
#    enabled: true
#    rotation: "@weekly"