apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-logging-stack-install
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "dogus": [
      {
        "name":"official/cas",
        "version":"7.0.8-11",
        "targetState":"present"
      },
      {
        "name":"k8s/nginx-ingress",
        "version":"1.11.1-4",
        "targetState":"present"
      },
      {
        "name":"k8s/nginx-static",
        "version":"1.26.3-1",
        "targetState":"present"
      },
      {
        "name":"official/postgresql",
        "version":"14.17-1",
        "targetState":"present"
      },
      {
        "name":"premium/grafana",
        "version":"11.5.2-1",
        "targetState":"present"
      },
      {
        "name":"premium/admin",
        "version":"2.13.2-1",
        "targetState":"present"
      },
    ],
    "components": [
      {
        "name":"k8s/k8s-minio",
        "version":"2024.11.7-2",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-ces-control",
        "version":"1.3.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-loki",
        "version":"3.3.2-1",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-promtail",
        "version":"2.9.1-7",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-prometheus",
        "version":"57.1.1-7",
        "targetState":"present"
      }
    ]}
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  allowDoguNamespaceSwitch: false
